#!/bin/bash
DEFAULT_SOURCE=$(pactl get-default-source)
DEFAULT_SINK=$(pactl get-default-sink)
echo "input: $DEFAULT_SOURCE"
echo "output: $DEFAULT_SINK"
#for playing audio through mic stream and output stream:
#PULSE_SINK="combined" ./parp -p...
pactl load-module module-null-sink \
  sink_name=virtual_mic \
  sink_properties=device.description=VirtualMic \
  channels=2 rate=48000 format=s16le


pactl load-module module-virtual-source \
  source_name=virtual_mic_source \
  master=virtual_mic.monitor \
  source_properties=device.description=VirtualMic-Input \
  channels=2 rate=48000 format=s16le

pactl set-default-source virtual_mic.monitor



#DO NOT PUT SPACES BETWEEN ARGUMENTS IN BASH
pactl load-module module-loopback source=$DEFAULT_SOURCE sink=virtual_mic latency_msec=25
sleep 0.5 #virtual mic needs a little time to be fully initialized
pactl load-module module-combine-sink sink_name=combined slaves=$DEFAULT_SINK,virtual_mic
