name: Lint

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang-tidy portaudio19-dev
          git clone https://github.com/PortAudio/portaudio.git

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: clang-tidy main.cpp -- -std=c++17 -I/usr/include -Iportaudio/src/common
